---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sanity-label-check
spec:
  params:
    - name: IMAGE_URL
      description: The fully qualified image name
    - name: POLICY_DIR
      description: "Path to the directory containing conftest policies"
      default: "/project/image/"
    - name: POLICY_NAMESPACE
      description: "Namespace for the conftest policy"
      default: "required_checks"

  results:
    - description: Test output
      name: HACBS_TEST_OUTPUT
  steps:
    - name: basic-sanity-checks-required-labels
      image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        skopeo inspect --no-tags docker://$(inputs.params.IMAGE_URL) | tee /tmp/image_inspect.json

        echo "Running conftest using $(inputs.params.POLICY_DIR) policy, $(inputs.params.POLICY_NAMESPACE) namespace"
        /usr/bin/conftest test --no-fail /tmp/image_inspect.json \
        --policy $(inputs.params.POLICY_DIR) --namespace $(inputs.params.POLICY_NAMESPACE) \
        --output=json | tee /tmp/sanity_label_check_output.json

        HACBS_ERROR_OUTPUT=$(jq -rc --arg date $(date +%s) --null-input \
          '{result: "ERROR", timestamp: $date}')
        HACBS_TEST_OUTPUT=$(jq -rce --arg date $(date +%s) \
          '.[] | { result: (if (.failures | length > 0) then "FAILURE" else "SUCCESS" end),
                   timestamp: $date,
                   namespace,
                   successes,
                   failures: (.failures // [])|map(.metadata.details.name)
                 }' /tmp/sanity_label_check_output.json || true)
        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
