---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: sanity-label-check
spec:
  params:
    - name: POLICY_DIR
      description: "Path to the directory containing conftest policies"
      default: "/project/image/"
    - name: POLICY_NAMESPACE
      description: "Namespace for the conftest policy"
      default: "required_checks"
  workspaces:
    - name: workspace
  results:
    - description: Test output
      name: HACBS_TEST_OUTPUT
  steps:
    - name: basic-sanity-checks-required-labels
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.10@sha256:ae276785973aaffb4554c1798cf629df33e7058b30c32b75bd8ada54b2afe42f
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)-$(params.POLICY_NAMESPACE)
      env:
        - name: POLICY_NAMESPACE
          value: $(params.POLICY_NAMESPACE)
        - name: POLICY_DIR
          value: $(params.POLICY_DIR)
      securityContext:
        capabilities:
          add:
            - SETFCAP
      script: |
        #!/usr/bin/env bash

        . /utils.sh
        if [ ! -s ../sanity-inspect-image/image_inspect.json ]; then
          echo "File ../sanity-inspect-image/image_inspect.json is not generated correctly, please check HACBS_TEST_OUTPUT of task sanity-inspect-image"
          HACBS_TEST_OUTPUT="$(make_result_json -r ERROR -t 'File ../sanity-inspect-image/image_inspect.json is not generated correctly, please check HACBS_TEST_OUTPUT of task sanity-inspect-image!')"
          echo "${HACBS_TEST_OUTPUT}" | tee $(results.HACBS_TEST_OUTPUT.path)
          exit 0
        fi

        CONFTEST_OPTIONS=""
        if [ -s "../sanity-inspect-image/base_image_inspect.json" ]; then
          CONFTEST_OPTIONS="-d=../sanity-inspect-image/base_image_inspect.json"
        fi

        echo "Running conftest using $POLICY_DIR policy, $POLICY_NAMESPACE namespace"
        /usr/bin/conftest test --no-fail ../sanity-inspect-image/image_inspect.json "${CONFTEST_OPTIONS}" \
        --policy $POLICY_DIR --namespace $POLICY_NAMESPACE \
        --output=json 2> stderr.txt | tee sanity_label_check_output.json

        if [ ! -z $(cat stderr.txt) ]; then
          echo "The sanity-label-check test meets the following error:"
          cat stderr.txt
        fi
        HACBS_ERROR_OUTPUT=$(make_result_json -r "ERROR")

        HACBS_TEST_OUTPUT=
        parse_hacbs_test_output $(context.task.name) conftest sanity_label_check_output.json || true

        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
