apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
  - path: hacbs-test.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
