apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |
      - op: replace
        path: /spec/tasks/2/taskRef/name
        value: configure-build-no-shared
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true
