apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: appstudio-tekton-bundle
spec:
  description: >-
    Bundle tekton manifests into OCI image and push to registry
  params:
    - name: output-image
    - name: path-context
      default: .
    - name: files
      default: "*.yaml *.yml"
  workspaces:
    - name: source
    - name: registry-auth
  steps:
    - name: appstudio-tekton-bundle
      image: quay.io/redhat-appstudio/appstudio-utils:v0.1.3
      workingDir: $(workspaces.source.path)/$(params.path-context)
      script: |
        #!/bin/bash

        echo "App Studio Tekton Bundle Creation: $(params.output-image)"

        AUTH=$(workspaces.registry-auth.path)/.dockerconfigjson
        
        FILES=""
        echo "Looking for files $(params.files) under $(params.path-context)"
        for FILE in $(ls $(params.files)); do
          echo "Found: $FILE"
          FILES="$FILES -f $FILE"
        done
        cat $(workspaces.registry-auth.path)/.dockerconfigjson
        if [ -f $AUTH ]; then
          mkdir -p $HOME/.docker
          cp $AUTH $HOME/.docker/config.json
        fi
        tkn bundle push $(params.output-image) $FILES
