apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-exists 
spec:
  description: >-
    Determine if an image already exists and output results. If the image does exist, then set results to true, else results to false
  params:
    - name: image-url
      description: Image URL for testing 
  results:
    - name: exists
      description: True if exists false otherwise
  workspaces:
    - name: source
      optional: true
  steps:
    - name: test-image-exists 
      image: appstudio-utils
      script: |
        #!/usr/bin/env bash   
        { set +x ;} 2> /dev/null 
        echo "App Studio Utility Task $(context.task.name)"     
        /appstudio-utils/util-scripts/$(context.task.name).sh \
          "$(params.image-url)" /tekton/results
