apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: configure-build
spec:
  description: >-
    App Studio Configure Build Secrets in Source.
  params:
    - name: shared-secret
      default: redhat-appstudio-user-workload
  results:
    - name: buildah-auth-param
      description: pass this to the build optional params to configure secrets
  workspaces:
    - name: source
  volumes:
    - name: default-push-secret
      csi:
        readOnly: true
        driver: csi.sharedresource.openshift.io
        volumeAttributes:
          sharedSecret: $(params.shared-secret)
  steps:
    - name: appstudio-configure-build
      image: quay.io/redhat-appstudio/appstudio-utils:4580b3ba3012095ff3981e50b6bbf753d4afd4c3
      volumeMounts:
        - name: default-push-secret
          mountPath: /secret/default-push-secret
      script: |
        #!/usr/bin/env bash
        echo "App Studio Configure Build"

        DEST=/workspace/source/.dockerconfigjson
        SHARED=/secret/default-push-secret/.dockerconfigjson
        if [ -f $SHARED ]; then
           jq -M -s '.[0] * .[1]' $SHARED ~/.docker/config.json > $DEST
        else
           cp ~/.docker/config.json $DEST
        fi
        chmod 644 $DEST
        echo -n "--authfile $DEST"  >  /tekton/results/buildah-auth-param
