---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-definitions-bundle-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "push"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[tasks/update-infra-deployments.yaml, tasks/git-clone.yaml, tasks/buildah.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - description: 'Source Repository URL'
        name: git-url
        type: string
      - description: 'Revision of the Source Repository'
        name: revision
        type: string
    tasks:
      - name: clone-repository
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: "$(params.revision)"
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: workspace
      - name: build-container
        params:
          - name: IMAGE
            value: quay.io/redhat-appstudio/appstudio-utils:{{ revision }}
          - name: CONTEXT
            value: appstudio-utils
        runAfter:
          - clone-repository
        taskRef:
          name: buildah
        workspaces:
          - name: source
            workspace: workspace
      - name: build-bundles
        params:
          - name: revision
            value: "$(params.revision)"
        runAfter:
          - build-container
        workspaces:
          - name: source
            workspace: workspace
        taskSpec:
          params:
            - name: revision
              type: string
          steps:
            - name: build-bundles
              image: quay.io/redhat-appstudio/appstudio-utils:{{ revision }}
              workingDir: $(workspaces.source.path)
              script: |
                #!/usr/bin/env bash
                MY_QUAY_USER=redhat-appstudio BUILD_TAG=$(params.revision) SKIP_BUILD=1 SKIP_INSTALL=1 hack/build-and-push.sh
          workspaces:
            - name: source
      - name: update-infra-repo
        runAfter:
          - build-bundles
        params:
          - name: ORIGIN_REPO
            value: $(params.git-url)
          - name: SCRIPT
            value: |
              BUNDLE=quay.io/redhat-appstudio/build-templates-bundle
              for file in $(git grep -l $BUNDLE); do
                sed -i "s|\($BUNDLE\):.*|\1:$(params.revision)|g" $file
              done
        taskRef:
          name: update-infra-deployments
        workspaces:
          - name: deploy-key
            workspace: deploy-key
    workspaces:
      - name: workspace
      - name: deploy-key
  serviceAccountName: pipeline
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: build-definitions-bundle-{{ revision }}
    - name: deploy-key
      secret:
        secretName: infra-deployments-deploy-key
